# Generated by Django 6.0.7 on 2026-07-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text="Identificador corto usado en la URL/pestaña, ej. 'japon'", unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('glifo', models.CharField(help_text='Símbolo o iniciales mostradas junto al nombre', max_length=10)),
                ('acento', models.CharField(help_text='Color de acento en formato hexadecimal, ej. #b8352b', max_length=7)),
                ('lema', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('cultura_titulo', models.CharField(max_length=200)),
                ('cultura_texto', models.TextField()),
                ('paisajes_titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el navbar')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glifo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='culturas.pais')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Paisaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=200)),
                ('epoca', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paisajes/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisajes', to='culturas.pais')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
